auto: true

baseurl: /

navigation:
- text: Biografie
  url: /biografie.html
- text: Werkwijze
  url: /werkwijze.html
- text: Schilderijen
  url: /portfolio/index.html
- text: Gastenboek
  url: /gastenboek.html
- text: Contact
  url: /contact.html